### ISSUE TITLE
Homepage: Make hero text rotate with images

### ISSUE THREAD

**Issue by gracecanfield** [vigetlabs/npm#196]
## Overview

**Page or Element Name**
Homepage Hero

**Example URL**
https://live-national-public-media-v2.pantheonsite.io/
	
**Related Trello card:**
https://trello.com/c/xxc1yalL

## Details

**Summary:**
Would like the copy and call to action button to be specific to each image and rotate together with the images.

**Current vs. Desired state:**
Currently images rotate, and one text option is displayed. We would like to be able to change the text and CTA together with the images in order to feature multiple CTAs here.

**Screenshots**
If applicable, attach screenshots to help explain your request.

**Comment by gracecanfield** [comment]
@justinvandenberg Should I be seeing a pause button? I do not:
https://live-national-public-media-v2.pantheonsite.io/

**Comment by mindywagner** [comment]
### Mobile Updates Needed:

**Header:**
- [ ] Reduce top & bottom padding on both white and blue versions of the mobile header (currently shows an added 10px top/bottom)
![Screen Shot 2019-12-03 at 9 19 45 AM](https://user-images.githubusercontent.com/67819/70059379-ad0ca000-15ae-11ea-855e-98691f765c10.png)

**Pause button:**

- [ ] Move Pause button to top on mobile (seems inaccessible if it’s buried at the bottom of the carousel)
- [ ] On hover, turn text to white so there’s an indication it’s clickable
- [ ] When paused, change the icon/indicator to the play button and the text to Play - make sure users can un-pause

**Hero image/text:**
- [ ] Reduce headline to 30px (similar to other page headlines)
- [ ] Pull image width into the main container
- [ ] Reduce top padding on hero container to 20px (currently 30px - see diagram attached)

![Screen Shot 2019-12-03 at 9 24 02 AM](https://user-images.githubusercontent.com/67819/70059373-ab42dc80-15ae-11ea-8cc8-ac58ffa6a45e.png)


### ~iPad Updates Needed:

- [ ] Pull the pause button up - spacing should be 20px below the image (similar to desktop)
- [ ] Reduce top & bottom padding on ~iPad width nav to 10px (currently 20px)

![Screen Shot 2019-12-03 at 9 33 18 AM](https://user-images.githubusercontent.com/67819/70060228-1f31b480-15b0-11ea-9a7f-b7917f2aa411.png)

**Comment by gracecanfield** [comment]
@justinvandenberg Additional thing:
* [ ] After a user clicks "pause" the "pause" text should change to "play" and the icon should change to a play icon. (otherwise the UX is confusing - the carousel pauses but the state of the pause text

**Comment by justinvandenberg** [comment]
@mindywagner we're switching to this one? 
<img width="922" alt="NPM_Comps_-_For_Buildout-2" src="https://user-images.githubusercontent.com/8126358/70083818-5ca33b80-15ca-11ea-94d7-fc47c695e478.png">

**Comment by mindywagner** [comment]
Yes - Grace and I chatted and it seemed necessary to get the shorter height they're looking for. Sorry there are so many iterations - I'll hide the old ones

**Comment by justinvandenberg** [comment]
@mindywagner I made this comment in Figma too, but "There's no real way to anchor the button to the image unless we include it in each (it would slide). Is that ok?"

**Comment by justinvandenberg** [comment]
@mindywagner I was unable to reproduce the image overflow on the left. I think it may have been resolved by one of the other things.

**Comment by mindywagner** [comment]
Hmmm - I don't think the button should slide or animate, so we should keep it separate it I guess.

**Comment by mindywagner** [comment]
> @mindywagner I was unable to reproduce the image overflow on the left. I think it may have been resolved by one of the other things.

For this - I'm still seeing it on test. I'm in Chrome. @gracecanfield do you see a sliver of the last image on the left hand side of the screen? 

Here's a screenshot:
![Screen Shot 2019-12-04 at 8 32 03 AM](https://user-images.githubusercontent.com/67819/70146630-93cc2800-1670-11ea-8856-9c28cd0a1109.png)

**Comment by gracecanfield** [comment]
@mindywagner I do not. ([screenshot of what I see](https://www.dropbox.com/s/6y2s33iiwmlci00/Screenshot%202019-12-04%2008.38.23.png?dl=0).

I played around with resizing my browser window and the closest I could get to repro was if the carousel slide effect happened _while_ I was in process of resizing my window. But I don't think that's anything to worry about.

@mindywagner Are you using the latest version of Chrome? Are you still seeing this after a hard refresh/clearing cache?

**Comment by mindywagner** [comment]
Most up to date Chrome, and it doesn't resolve after a hard refresh. I also see it when I bring the site up in an incognito window. 

Here's what it looks like: 
https://drive.google.com/file/d/1A96khflL-_s56sBD1w4rDPFaz-ISJLeI/view?usp=sharing

**Comment by gracecanfield** [comment]
@mindywagner @justinvandenberg While i'm still not able to repro on my machine, I asked @jessicasheng15 to test and she (running the latest version of Chrome) is seeing the exact same behavior as Mindy, so it looks like it's not just a weird one-off thing.

**Comment by justinvandenberg** [comment]
@mindywagner @jessicasheng15 @gracecanfield are you still seeing the overlap after the deploy (about 1 hour ago)?
